services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: